import type { Metadata } from "next";
import { Inter, Unica_One } from 'next/font/google'
import "./globals.css";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: '500',
});

const unicaOne = Unica_One({
  weight: '400', 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-unica'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${unicaOne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
